#pragma once

struct func ID3D11Device_func_table[] = {
	"QueryInterface", 1,
	"AddRef", 1,
	"Release", 1,
	"CreateBuffer", 4,
	"CreateTexture1D", 4,
	"CreateTexture2D", 4,
	"CreateTexture3D", 4,
	"CreateShaderResourceView", 4,
	"CreateUnorderedAccessView", 4,
	"CreateRenderTargetView", 4,
	"CreateDepthStencilView", 4,
	"CreateInputLayout", 6,
	"CreateVertexShader", 5,
	"CreateGeometryShader", 5,
	"CreateGeometryShaderWithStreamOutput", 10,
	"CreatePixelShader", 5,
	"CreateHullShader", 5,
	"CreateDomainShader", 5,
	"CreateComputeShader", 5,
	"CreateClassLinkage", 2,
	"CreateBlendState", 3,
	"CreateDepthStencilState", 3,
	"CreateRasterizerState", 3,
	"CreateSamplerState", 3,
	"CreateQuery", 3,
	"CreatePredicate", 3,
	"CreateCounter", 3,
	"CreateDeferredContext", 3,
	"OpenSharedResource", 4,
	"CheckFormatSupport", 3,
	"CheckMultisampleQualityLevels", 4,
	"CheckCounterInfo", 2,
	"CheckCounter", 10,
	"CheckFeatureSupport", 4,
	"GetPrivateData", 4,
	"SetPrivateData", 4,
	"SetPrivateDataInterface", 3,
	"GetFeatureLevel", 1,
	"GetCreationFlags", 1,
	"GetDeviceRemovedReason", 1,
	"GetImmediateContext", 2,
	"SetExceptionMode", 2,
	"GetExceptionMode", 1,
};

uint32_t ID3D11DeviceFuncsNum = sizeof(ID3D11Device_func_table) / sizeof(struct func);
